// src/routes/index.svelte
<script>
  import Image from 'svelte-image'
</script>

<svelte:head>
  <title>Hunam - Home</title>
  <meta
    name="description"
    content="Hunam's personal website, see my projects & how I made those."
  />
  <link
    rel="preload"
    href="/fonts/Inconsolata-UltraExpanded-Black.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
  <link
    rel="preload"
    href="/fonts/Inconsolata-Expanded-Black.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
  <style>
    body {
      max-height: 100vh;
      overflow: hidden;
    }
  </style>
</svelte:head>
<main>
  <section>
    <Image
      src="/assets/me.jpg"
      alt="Image of myself"
      lazy={false}
      class="me-img"
      wrapperClass="me-wrapper"
      placeholderClass="me-placeholder"
    />
    <div>
      <h1>Hi, I'm Hunam.</h1>
      <h2>I do modern development.</h2>
    </div>
  </section>
</main>
<footer>
  <a href="https://github.com/hunam6" id="github">Github</a>
  <a href="https://twitter.com/hunam_" id="twitter">Twitter</a>
</footer>

<style>
  @font-face {
    font-family: 'Inconsolata UltraExpanded Black';
    font-display: swap;
    src: url(/fonts/Inconsolata-UltraExpanded-Black.woff2) format('woff2');
  }
  @font-face {
    font-family: 'Inconsolata Expanded Black';
    font-display: swap;
    src: url(/fonts/Inconsolata-Expanded-Black.woff2) format('woff2');
  }

  section {
    background: url('/assets/stroke-mobile.svg') no-repeat;
    position: relative;
    height: 100vh;
    margin: 5.5rem 0.5rem 0 2rem;
  }
  :global(.me-img) {
    border-radius: 50%;
    width: 35vw;
    height: 35vw;
    border: 4px solid var(--yellow);
  }
  :global(.me-wrapper) {
    border-radius: 50%;
    position: absolute;
    right: 0;
    top: 0;
    transform: translateY(-50%);
    width: 35vw !important;
    height: 35vw !important;
  }
  :global(.me-placeholder) {
    border-radius: 50%;
  }
  div {
    padding: 20vh 0 0 10vw;
    font-family: 'Inconsolata UltraExpanded Black';
  }
  h1 {
    color: var(--white);
    font-size: 1.25rem;
    text-shadow: -3px -3px 0 var(--bg), 3px -3px 0 var(--bg),
      -3px 3px 0 var(--bg), 3px 3px 0 var(--bg), 4px 4px 0 var(--yellow),
      5px 5px 0 var(--yellow), 6px 6px 0 var(--yellow), 7px 7px 0 var(--yellow);
  }
  h2 {
    color: var(--bg);
    font-size: 1.25rem;
    text-shadow: -1px 0 0 var(--yellow), -1px 1px 0 var(--yellow),
      0 -1px 0 var(--yellow), 0 1px 0 var(--yellow), 1px -1px 0 var(--yellow),
      1px 0 0 var(--yellow);
  }

  footer {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    position: absolute;
    bottom: 0;
    right: 0;
    padding: 1rem;
    gap: 2vh;
  }
  footer > a {
    color: var(--light-gray);
    text-decoration: none;
    display: flex;
    align-items: center;
    font-size: 1.25rem;
    font-family: 'Inconsolata Expanded Black', sans-serif;
  }
  a::after {
    margin-left: 1rem;
  }
  #github::after {
    content: url('/assets/github.svg');
  }
  #twitter::after {
    content: url('/assets/twitter.svg');
  }

  @media (min-width: 768px) {
    section {
      background: url('/assets/stroke-desktop.svg') no-repeat;
      margin: 25vh 20vw 0 15vw;
    }
    :global(.me-img) {
      height: 15rem;
      width: 15rem;
      border-width: 10px;
    }
    :global(.me-wrapper) {
      height: 15rem !important;
      width: 15rem !important;
    }
    div {
      padding: 10vh 0 0 5vw;
    }

    h1 {
      letter-spacing: 0.5rem;
    }
    h1,
    h2 {
      font-size: 2.5rem;
      white-space: nowrap;
    }
    footer {
      flex-direction: row;
    }
    footer > a {
      font-size: 1rem;
    }
  }

  @media (min-width: 1441px) {
    :global(.me-img) {
      height: 17.5rem;
      width: 17.5rem;
    }
    :global(.me-wrapper) {
      height: 17.5rem !important;
      width: 17.5rem !important;
    }

    h1,
    h2 {
      font-size: 3.5rem;
    }

    footer > a {
      font-size: 1.25rem;
    }
  }
</style>

// src/routes/index.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { SlickLink } from "~/components/slick-link";
import style from "./index.css?inline";

export const Social = component$(
  (props: { name: string; link: string; icon: string }) => {
    return (
      <SlickLink
        href={props.link}
        class="flex items-center justify-end gap-4 hover:text-white"
      >
        <p>{props.name}</p>
        <img src={props.icon} alt={props.name} class="h-8 w-8" />
      </SlickLink>
    );
  }
);

export default component$(() => {
  useStylesScoped$(style);

  return (
    <>
      <main
        class="
          relative mx-auto mt-[20vh]
          flex h-[60vh] w-10/12
          flex-col bg-[url('/assets/stroke-mobile.svg')] bg-no-repeat pl-8 pt-36 font-['Inconsolata_UltraExpanded_Black'] md:w-7/12 md:bg-[url('/assets/stroke-desktop.svg')] md:pl-20
          md:pt-32"
      >
        <img
          src="/assets/me.jpg"
          alt="A photo of myself with a cool bucket hat."
          class="
            absolute top-0 -right-5 h-32
            w-32 -translate-y-1/2 rounded-full border-4
            border-yellow md:h-56 md:w-56 md:border-[10px]"
        />
        <h3 class="custom-text-shadow-1 text-xl text-white md:text-4xl">
          Hi, I'm Hunam.
        </h3>
        <h3 class="custom-text-shadow-2 mt-10 w-76 text-xl text-dark md:w-auto md:text-4xl">
          I craft quality products.
        </h3>
      </main>
      <footer
        class="
        absolute right-4 bottom-4
        flex flex-col gap-6 text-lg
        text-light-grey md:flex-row md:text-xl"
      >
        <Social
          name="Github"
          link="https://github.com/hunam6"
          icon="/assets/icons/github.svg"
        />
        <Social
          name="Twitter"
          link="https://twitter.com/hunam_"
          icon="/assets/icons/twitter.svg"
        />
      </footer>
    </>
  );
});

export const head: DocumentHead = {
  title: "Hunam - Home",
  meta: [
    {
      name: "description",
      content: "Hunam's personal website & portfolio homepage.",
    },
  ],
};
