// src/routes/projects.svelte
<script>
  import Image from 'svelte-image'
</script>

<svelte:head>
  <title>Hunam - Projects</title>
  <meta
    name="description"
    content="List of projects I've made, click keep reading to find the blog post coresponding to the project."
  />
  <link
    rel="preload"
    href="/fonts/Inconsolata-Black.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
  <link
    rel="preload"
    href="/fonts/Inconsolata-Condensed-Bold.woff2"
    as="font"
    type="font/woff2"
    crossOrigin="anonymous"
  />
</svelte:head>
<main>
  <article>
    <div class="container">
      <div>
        <p class="name">NAME</p>
        <h2>Go2V</h2>
        <div class="separator" />
        <p class="description">
          Go2V is a Go to V source code translator. This software is able to
          translate code written in Go-lang into V-lang code.
        </p>
      </div>
      <a href="https://github.com/vlang/go2v">Keep reading...</a>
    </div>
    <Image
      src="/assets/projects/go2v.jpeg"
      alt={'Go2V'}
      lazy={false}
      class="project-img"
      wrapperClass="project-wrapper"
      placeholderClass="project-placeholder"
    />
  </article>
  <article>
    <div class="container">
      <div>
        <p class="name">NAME</p>
        <h2>Goodgle</h2>
        <div class="separator" />
        <p class="description">
          Goodgle is a Google-based metasearch engine that entirely anonymizes
          its users while still giving a decent search experience and a
          completely redesigned user interface.
        </p>
      </div>
      <a href="https://github.com/hunam6/goodgle">Keep reading...</a>
    </div>
    <Image
      src="/assets/projects/goodgle.png"
      alt={'Goodgle'}
      lazy={false}
      class="project-img"
      wrapperClass="project-wrapper"
      placeholderClass="project-placeholder"
    />
  </article>
</main>

<style>
  @font-face {
    font-family: 'Inconsolata Black';
    font-display: swap;
    src: url(/fonts/Inconsolata-Black.woff2) format('woff2');
  }
  @font-face {
    font-family: 'Inconsolata Condensed Bold';
    font-display: swap;
    src: url(/fonts/Inconsolata-Condensed-Bold.woff2) format('woff2');
  }

  main {
    margin: 2.5rem 0 0 0;
  }
  article {
    width: 80%;
    margin: 0 auto;
    background: var(--dark-gray);
    border-radius: 2.5rem;
    margin-bottom: 2rem;
    justify-content: space-between;
  }

  .container {
    padding: 0.5rem 1rem 1rem 1rem;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    align-content: space-between;
  }
  .name {
    font-family: 'Inconsolata Black';
    color: var(--gray);
    margin: 0.5rem 0 0.25rem 0;
  }
  h2 {
    font-family: 'Inconsolata Condensed Bold';
    font-size: 1.25rem;
    color: var(--white);
    margin: 0;
    letter-spacing: 0.125rem;
  }
  .separator {
    width: 100%;
    height: 2px;
    background: linear-gradient(
      to right,
      rgb(255 255 255/0),
      rgb(255 255 255/0.1),
      rgb(255 255 255/0)
    );
    margin: 0.5rem 0;
  }
  p {
    color: var(--white);
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 6;
    overflow: hidden;
    margin: 0 0 0.5rem 0;
  }
  a {
    text-decoration: none;
    color: var(--yellow);
    margin-bottom: 1rem;
    font-size: 1rem;
  }

  :global(.project-img) {
    border-radius: 0 0 2.5rem 2.5rem;
  }

  @media (min-width: 768px) {
    article {
      width: 65vw;
      display: flex;
      margin-bottom: 5rem;
      height: 40vh;
    }

    article:nth-child(even) {
      flex-direction: row-reverse;
    }

    .container {
      width: 32.5vw;
      padding: 2rem;
    }
    .name {
      font-size: 1.1rem;
    }
    h2 {
      font-size: 1.3rem;
    }
    .separator {
      margin: 1rem 0;
    }
    .description {
      font-size: 1rem;
      line-height: 130%;
      margin-bottom: 1rem;
    }
    a {
      font-size: 1rem;
      letter-spacing: 0.1rem;
    }

    :global(.project-wrapper) {
      max-width: 32.5vw;
      height: 40vh;
    }

    :global(.project-wrapper > div > div) {
      height: 40vh;
    }

    :global(.project-img) {
      border-radius: 0 2.5rem 2.5rem 0;
      height: 40vh;
    }
    :global(article:nth-child(even) .project-img) {
      border-radius: 2.5rem 0 0 2.5rem;
    }
  }

  @media (min-width: 1441px) {
    .name,
    h2 {
      font-size: 1.5rem;
    }
    .description,
    a {
      font-size: 1.3rem;
    }
  }
</style>

// src/routes/projects/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { CardHeader } from "~/components/card-header";
import { SlickLink } from "~/components/slick-link";

interface ProjectProps {
  name: string;
  description: string;
  image: string;
  link: string;
}

export const Project = component$((props: ProjectProps) => {
  return (
    <article
      class="
      overflow-hidden
      rounded-5xl bg-dark-grey
      md:flex md:h-72 md:even:flex-row-reverse"
    >
      <div class="p-5 md:w-1/2">
        <CardHeader name={props.name} />
        <p class="text-white md:mb-2 md:mt-8">{props.description}</p>
        <SlickLink href={props.link} class="text-yellow md:block">
          Keep reading...
        </SlickLink>
      </div>
      <div class="bg-white md:w-1/2">
        <img src={props.image} alt={props.name} class="md:mx-auto md:h-72" />
      </div>
    </article>
  );
});

export default component$(() => {
  return (
    <>
      <main
        class="
          mx-auto mb-10 mt-5
          flex w-10/12 flex-col gap-10 md:w-8/12"
      >
        <Project
          name="Go2V"
          description="Go2V is a fully automated Go-lang to V-lang source code translator."
          image="/assets/projects/go2v.jpeg"
          link="https://github.com/vlang/go2v"
        />
        <Project
          name="Goodgle"
          description="The beautiful & private meta-search engine based on Google."
          image="/assets/projects/goodgle.png"
          link="https://github.com/hunam6/goodgle"
        />
      </main>
    </>
  );
});

export const head: DocumentHead = {
  title: "Hunam - Projects",
  meta: [
    {
      name: "description",
      content: "Open source projects I made.",
    },
  ],
};
